name: Rest API CI

permissions:
  contents: write
  packages: write

env:
  VERSION: v5

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      run_all:
        description: "Run all jobs"
        required: false
        default: "true"
      run_test:
        description: "Run only test"
        required: false
        default: "true"

jobs:
  test:
    if: |
      github.event_name != 'workflow_dispatch' ||
      github.event.inputs.run_all == 'true' ||
      github.event.inputs.run_test == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set up Go
        with:
          go-version: "1.25"
        uses: actions/setup-go@v6
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test -v -coverprofile=coverage.out ./...

      - name: Extract coverage percentage
        id: coverage
        run: |
          COVERAGE=$(go tool cover -func=coverage.out | grep total: | awk '{print substr($3, 1, length($3)-1)}')
          echo "COVERAGE=$COVERAGE" >> $GITHUB_ENV

      - name: Generate coverage badge
        run: |
          COLOR="red"
          VALUE=${COVERAGE%.*}
          if [ "$VALUE" -ge 90 ]; then COLOR="brightgreen";
          elif [ "$VALUE" -ge 80 ]; then COLOR="green";
          elif [ "$VALUE" -ge 70 ]; then COLOR="yellowgreen";
          elif [ "$VALUE" -ge 60 ]; then COLOR="yellow";
          elif [ "$VALUE" -ge 50 ]; then COLOR="orange";
          fi
          curl -s "https://img.shields.io/badge/Coverage-${COVERAGE}%25-${COLOR}.svg" > coverage.svg

      - name: Commit coverage badge
        uses: EndBug/add-and-commit@v9
        with:
          add: "--force coverage.svg"
          message: "Update coverage badge"
          author_name: github-actions
          author_email: github-actions@github.com

  build_and_push:
    if: |
      github.event_name != 'workflow_dispatch' ||
      github.event.inputs.run_all == 'true' ||
      github.event.inputs.run_build_and_push == 'true'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/rest-api:${{ env.VERSION }}
          file: Dockerfile
      - name: Build and Push latest
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/rest-api:latest
          file: Dockerfile
